# Keycloak OIDC configuration
quarkus.oidc.client-id=cx-ml-cli
quarkus.oidc.auth-server-url=${KEYCLOAK_URL:http://localhost:8080/auth/realms/master}
quarkus.oidc.credentials.secret=${CLIENT_SECRET:secret}
quarkus.oidc.token-path=/protocol/openid-connect/token

# REST Client for artifact store API
quarkus.rest-client.artifact-store-api.url=${API_BASE_URL:http://artifact-store.local}
quarkus.rest-client.artifact-store-api.scope=javax.inject.Singleton

# CLI configuration
quarkus.picocli.program-name=cx-ml-cli

# Logging (optional)
quarkus.log.level=INFO

# Native image compatibility
quarkus.native.enable-vm-inspection=false
quarkus.native.additional-build-args=--allow-incomplete-classpath

artifact-api/mp-rest/url=http://localhost:8083
artifact-api/mp-rest/scope=javax.inject.Singleton

# ?????: ??????????? ?????? ??????? quarkus.rest-client
quarkus.rest-client."serving-api".url=http://localhost:8081
quarkus.rest-client."serving-api".scope=jakarta.inject.Singleton

# ??? artifact-api (?????????, ????? ? ??? ??? ???????)
quarkus.rest-client."artifact-api".url=http://localhost:8083
quarkus.rest-client."artifact-api".scope=jakarta.inject.Singleton


quarkus.oidc-client.auth-server-url=http://localhost:8082/realms/model-registry-realm
quarkus.oidc-client.client-id=model-registry-app
quarkus.oidc-client.credentials.secret=LZbXY16jR0BRFazUKO3qTAoqXL3Uoet7
quarkus.oidc-client.grant.type=password
# ????????? ?????????????? ???????????, ???? ?? ????? ??????????? ??? ?????
quarkus.oidc-client.early-tokens-acquisition=false