# CLI configuration
quarkus.picocli.program-name=cx-ml-cli

# Logging (optional)
quarkus.log.level=INFO

# Native image compatibility
quarkus.native.enable-vm-inspection=false
quarkus.native.additional-build-args=--allow-incomplete-classpath

# ?????: ??????????? ?????? ??????? quarkus.rest-client
quarkus.rest-client."serving-api".url=http://localhost:8081
quarkus.rest-client."serving-api".scope=jakarta.inject.Singleton

# ??? artifact-api (?????????, ????? ? ??? ??? ???????)
quarkus.rest-client."artifact-api".url=http://localhost:8083
quarkus.rest-client."artifact-api".scope=jakarta.inject.Singleton